### PR TITLE
Bug Fix: Customer can lend multiple copies of a book

### LINKED ISSUE #1: Customer can lend multiple copies of a book
## Problem Statement
As a general lending rule in a library, a customer cannot borrow multiple copies of the same book at a given time, only one copy is allowed. However, lending multiple copies of the same book is supported now.

### Case 1
Calling the `lendBooks` operation twice with same books list goes through successfully:
```graphql
mutation {
  lendBooks(cart: {
    customerId: "d40b97c1-711d-4a80-9519-9b6635ff6a2b", 
    books: [
        "e05e0641-7e96-11ec-809a-0242ac110002", 
        "e05e07f0-7e96-11ec-809a-0242ac110002"
    ]}) {
    ... on Customer {
      id
      lendings {
        id
        dueOn
        book {
          id
          name
        }
      }
    }
    ... on BookStoreError {
      message
      status
    }
  }
}
```
> Expected behaviour: the second operation should fail
### Case 2
Calling the `lendBooks` operation with duplicate book ids goes through successfully:
```graphql
mutation {
  lendBooks(cart: {
    customerId: "d40b97c1-711d-4a80-9519-9b6635ff6a2b", 
    books: [
        "e05e0641-7e96-11ec-809a-0242ac110002", 
        "e05e0641-7e96-11ec-809a-0242ac110002"
    ]}) {
    ... on Customer {
      id
      lendings {
        id
        dueOn
        book {
          id
          name
        }
      }
    }
    ... on BookStoreError {
      message
      status
    }
  }
}
```
> Expected behaviour: this operation should fail

## Solution
Adjust the application to suit the above behaviour

### PR DESCRIPTION
**Pull request by rubal-98**
Following are the changes made for the cases of the bugs-
Case 1: Checking the data by adding in the set.
Case 2: Checking if the book is already lent to the customer with ACTIVE status

Fix: #1

### CODE REVIEW

File: bookstore-service/src/main/java/org/people/weijuly/bookstore/graphql/impl/mutation/LendBooksMutationResolverImpl.java [hunk 1]
```diff
@@ -63,7 +68,8 @@ private void updateCopies(String bookId) {
     }
 
     private void validate(CartInModel cartIn) {
-        if (cartIn.getBooks().isEmpty()) {
+        List<String> booksInCart= cartIn.getBooks();
```
Comment (weijuly) [inline bookstore-service/src/main/java/org/people/weijuly/bookstore/graphql/impl/mutation/LendBooksMutationResolverImpl.java]: space before `=`

File: bookstore-service/src/main/java/org/people/weijuly/bookstore/graphql/impl/mutation/LendBooksMutationResolverImpl.java [hunk 2]
```diff
@@ -72,13 +78,27 @@ private void validate(CartInModel cartIn) {
                         String.format("Customer with id: %s cannot be found", cartIn.getCustomerId()),
                         HttpStatus.BAD_REQUEST
                 ));
-        for (String bookId : cartIn.getBooks()) {
+        Set<String> booksSet = new HashSet<>(booksInCart);
+        if (booksSet.size() < booksInCart.size()) {
```
Comment (weijuly) [inline bookstore-service/src/main/java/org/people/weijuly/bookstore/graphql/impl/mutation/LendBooksMutationResolverImpl.java]: Instead of creating new variable, we can check like this `if (cartIn.getBooks().size() != new HashSet<>(cartIn.getBooks()).size())`

**Review by weijuly — CHANGES_REQUESTED** [review]
please address the review comments

**Review by weijuly — APPROVED** [review]
LGTM
